### ISSUE TITLE
Error: spawn EMFILE

### ISSUE THREAD

**Issue by ghost** [fmovlex/desprite#1]
```
child_process.js:945
    throw errnoException(process._errno, 'spawn');
          ^
Error: spawn EMFILE
    at errnoException (child_process.js:998:11)
    at ChildProcess.spawn (child_process.js:945:11)
    at exports.spawn (child_process.js:733:9)
    at gm._spawn (/desprite/node_modules/gm/lib/command.js:181:16)
    at /desprite/node_modules/gm/lib/command.js:73:12
    at series (/desprite/node_modules/gm/node_modules/array-series/index.js:11:36)
    at gm._preprocess (/desprite/node_modules/gm/lib/command.js:149:5)
    at gm.write (/desprite/node_modules/gm/lib/command.js:71:10)
    at doSplit (/desprite/desprite.js:78:3)
    at Object.<anonymous> (/Downloads/desprite/desprite.js:103:2)
```

**Comment by fmovlex** [comment]
Added an option to limit the child processes started by gm (default is 50, should be fine)

**Comment by ghost** [comment]
:+1:
